export const LOGIN_REQUEST = "LOGIN_REQUEST"
export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGIN_FAILURE = "LOGIN_FAILURE"


export const FETCH_ALL_PRODUCT = "FETCH_ALL_PRODUCT"
export const FETCH_ALL_PRODUCT_SUCCESS = "FETCH_ALL_PRODUCT_SUCCESS"
export const FETCH_ALL_PRODUCT_FAILURE = "FETCH_ALL_PRODUCT_FAILURE"


export const ADD_PRODUCT = "FETCH_ALL_PRODUCT"
export const ADD_PRODUCT_SUCCESS = "FETCH_ALL_PRODUCT_SUCCESS"
export const ADD_PRODUCT_FAILURE = "FETCH_ALL_PRODUCT_FAILURE"


export const UPDATE_PRODUCT = "FETCH_ALL_PRODUCT"
export const UPDATE_PRODUCT_SUCCESS = "FETCH_ALL_PRODUCT_SUCCESS"
export const UPDATE_PRODUCT_FAILURE = "FETCH_ALL_PRODUCT_FAILURE"


export const DELETE_PRODUCT = "FETCH_ALL_PRODUCT"
export const DELETE_PRODUCT_SUCCESS = "FETCH_ALL_PRODUCT_SUCCESS"
export const DELETE_PRODUCT_FAILURE = "FETCH_ALL_PRODUCT_FAILURE"